### ISSUE TITLE
Inconsistent instructions re: empty lines after status line

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-http-server#20]
Feedback from one user: 

> I noticed a minor issue in the HTTP server challenge. The examples have a blank line between the start line and headers but the spec does not specify that: https://datatracker.ietf.org/doc/html/rfc9112#name-message-format

> Also, there's the following statement in the spec:

> A sender MUST NOT send whitespace between the start-line and the first header field.

Similar feedback from another user: 

<img width="1252" alt="Screenshot 2023-11-30 at 11 41 42" src="https://github.com/codecrafters-io/build-your-own-http-server/assets/3893573/17cb9219-aa0b-4bc7-b6c4-521ca321b3e7">

**Comment by sherubthakur** [comment]
Fixed in https://github.com/codecrafters-io/build-your-own-http-server/commit/206df568063f264a3cb1e25e066a66c5d7f43a0d
